### model
model_name_or_path: Qwen/Qwen2-7B
adapter_name_or_path: saves/cangjie-qwen2-7b/lora/pretrain/checkpoint-19920
enable_liger_kernel: true

### method
stage: sft
do_train: true

### dataset
dataset: sft_cangjie,sft_cangjie_selfdebug,code_qa_10K,sharegpt_cleaned
template: qwen
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16
packing: false
tokenized_path: tmp_dataset/cangjie-qwen2-7b/lora/sft

### output
output_dir: saves/cangjie-qwen2-7b/lora/sft
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 100
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 100
