### model
model_name_or_path: Qwen/Qwen2-7B
adapter_name_or_path: saves/cangjie-qwen2-7b/lora/sft/checkpoint-14900
enable_liger_kernel: true

### method
stage: kto
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.0

pref_beta: 0.1

### dataset
dataset: kto_cangjie_full
template: qwen
cutoff_len: 512
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
packing: false
# tokenized_path: tmp_dataset/cangjie-qwen2-7b/lora/kto

### output
output_dir: saves/cangjie-qwen2-7b/lora/kto
logging_steps: 10
save_steps: 50
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5.0e-6
num_train_epochs: 30.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 100
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
